"""YouTube / Script / Image analyzer endpoints — all Gemini-powered."""
from __future__ import annotations
import asyncio
import json
import logging
import re
import shutil
import tempfile
import uuid
from pathlib import Path
from typing import Optional
from fastapi import APIRouter, HTTPException, UploadFile, File, Form
from pydantic import BaseModel

from ..config import OUTPUT_DIR, DATA_DIR
from ..services.gemini import generate_text, describe_image
from ..ws_hub import hub

log = logging.getLogger("navtools.analyzer")
router = APIRouter(prefix="/api/analyzer", tags=["analyzer"])


def _write_netscape_cookies(path: Path, cookies: list[dict]) -> None:
    """Write browser cookies (harvested by the extension) to a Netscape
    cookies.txt that yt-dlp accepts."""
    lines = ["# Netscape HTTP Cookie File", "# Auto-generated by RedOne extension"]
    for c in cookies:
        domain = (c.get("domain") or "").strip()
        if not domain or not c.get("name"):
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        try:
            expiry = int(c.get("expirationDate") or 0)
        except Exception:
            expiry = 0
        lines.append("\t".join([
            domain, include_sub, c.get("path") or "/", secure,
            str(expiry), c.get("name") or "", c.get("value") or "",
        ]))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


class ScriptAnalyzeRequest(BaseModel):
    script: str
    num_scenes: int = 5
    auto_detect_scenes: bool = True
    style_preset: Optional[str] = None
    style_lock: Optional[str] = None
    global_context: Optional[str] = None
    voice_gender: str = "female"
    character_aliases: Optional[dict] = None  # {"@nv1": "tên nhân vật"}


def _build_script_prompt(req: ScriptAnalyzeRequest) -> str:
    aliases = req.character_aliases or {}
    alias_lines = "\n".join(f"  {k}: {v}" for k, v in aliases.items()) or "  (no characters)"
    style = req.style_preset or "Cinematic"
    scene_directive = (
        "Auto-detect the optimal number of scenes (4-10)."
        if req.auto_detect_scenes
        else f"Split into EXACTLY {req.num_scenes} scenes."
    )
    return f"""You are a professional film director. Convert the following script into a structured video storyboard.

SCRIPT:
\"\"\"
{req.script.strip()}
\"\"\"

CHARACTERS:
{alias_lines}

STYLE: {style}
{('STYLE LOCK (use verbatim): ' + req.style_lock) if req.style_lock else ''}
{('GLOBAL CONTEXT: ' + req.global_context) if req.global_context else ''}
VOICE GENDER for narration: {req.voice_gender}

INSTRUCTIONS:
{scene_directive}

For EACH scene, output a JSON object with these keys:
- "scene": integer scene number
- "shot": one of [Extreme Wide Shot, Wide Shot, Medium Shot, Medium Close-Up, Close-Up, Extreme Close-Up, Over-the-Shoulder, POV]
- "camera": one of [Static, Pan Left, Pan Right, Tilt Up, Tilt Down, Zoom In, Zoom Out, Push In, Pull Out, Dolly, Tracking, Aerial]
- "characters": array of character aliases visible in this scene (from CHARACTERS above)
- "narration": 1-2 sentences of Vietnamese narration in {req.voice_gender} voice
- "prompt": A complete English Veo 3 prompt — describe subject, action, environment, lighting, camera, style. Include the style description.

Output ONLY a JSON array of scenes. No prose, no markdown fences."""


@router.post("/script")
async def analyze_script(body: ScriptAnalyzeRequest):
    """One-shot Gemini call to plan script into scenes."""
    if not body.script.strip():
        raise HTTPException(400, "Script is empty")
    prompt = _build_script_prompt(body)
    try:
        result = await generate_text(
            prompt,
            response_mime_type="application/json",
        )
        text = result["text"]
        text = re.sub(r"^```(?:json)?\s*", "", text.strip())
        text = re.sub(r"\s*```$", "", text)
        scenes = json.loads(text)
        return {
            "scenes": scenes,
            "model_used": result["model_used"],
            "fallback_log": result["fallback_log"],
        }
    except json.JSONDecodeError as e:
        raise HTTPException(500, f"AI returned invalid JSON: {e}")
    except Exception as e:
        raise HTTPException(500, f"AI error: {e}")


@router.post("/regenerate-scene")
async def regenerate_scene(req: dict):
    """Regenerate a single scene with higher temperature."""
    script = req.get("script", "")
    scenes = req.get("scenes", [])
    idx = int(req.get("scene_index", 0))
    if idx < 0 or idx >= len(scenes):
        raise HTTPException(400, "Invalid scene index")
    existing = scenes[idx]
    prompt = f"""Regenerate ONLY scene {existing['scene']} with a DIFFERENT shot, camera, and angle.
Keep the same narration intent but change the cinematography.

ORIGINAL SCENE: {json.dumps(existing, ensure_ascii=False)}

Output a single JSON object (NOT an array)."""
    try:
        result = await generate_text(prompt, response_mime_type="application/json")
        new_scene = json.loads(re.sub(r"^```(?:json)?\s*|\s*```$", "", result["text"].strip()))
        scenes[idx] = new_scene
        return {"scene": new_scene, "model_used": result["model_used"]}
    except Exception as e:
        raise HTTPException(500, f"Regenerate failed: {e}")


# ---------------- YouTube / TikTok analyzer ----------------

class YouTubeAnalyzeRequest(BaseModel):
    url: str
    style_preset: Optional[str] = None
    style_lock: Optional[str] = None
    global_context: Optional[str] = None
    use_whisper: bool = False
    quick_mode: bool = True
    voice_gender: str = "female"
    character_aliases: Optional[dict] = None
    max_scenes: int = 12


def _detect_platform(url: str) -> str:
    if "tiktok.com" in url:
        return "tiktok"
    if "youtube.com" in url or "youtu.be" in url:
        return "youtube"
    return "unknown"


@router.post("/youtube")
async def analyze_youtube(body: YouTubeAnalyzeRequest):
    """Download video via yt-dlp, then run Gemini analysis on the video itself."""
    if not body.url.strip():
        raise HTTPException(400, "URL required")
    platform = _detect_platform(body.url)
    if platform == "unknown":
        raise HTTPException(400, "Unsupported URL (only YouTube/TikTok)")

    try:
        import yt_dlp
    except Exception:
        raise HTTPException(500, "yt-dlp not installed. Run: pip install yt-dlp")

    tmp = Path(tempfile.mkdtemp(prefix="navtools_yt_"))
    out_template = str(tmp / "video.%(ext)s")
    # Route yt-dlp's own ERROR/console spam to debug — our try/except turns
    # real failures into a clean HTTPException, so its stderr just adds noise.
    class _YtdlpLogger:
        def debug(self, m): pass
        def info(self, m): pass
        def warning(self, m): pass
        def error(self, m): log.debug(f"[yt-dlp] {m}")

    try:
        from ..services.ffmpeg_utils import find_ffmpeg
        _ffmpeg = find_ffmpeg()
    except Exception:
        _ffmpeg = None
    base_opts = {
        "outtmpl": out_template,
        # Prefer a single combined ≤720 file (no ffmpeg needed); else MERGE
        # best video+audio (needs ffmpeg) — many YouTube videos have NO
        # progressive/combined format, which caused "Requested format is not
        # available" even after cookies got us past the bot wall.
        "format": (
            "best[ext=mp4][height<=720]/best[height<=720]/"
            "bestvideo[height<=720]+bestaudio/best/bestvideo+bestaudio"
        ),
        "merge_output_format": "mp4",
        "quiet": True,
        "no_warnings": True,
        "logger": _YtdlpLogger(),
        # "Requested format is not available" with valid cookies usually means
        # YouTube hid the formats behind a PO Token for the default `web`
        # client. Alternate player clients (android/ios/tv) still return real
        # formats. yt-dlp tries them in order until one yields formats.
        "extractor_args": {
            "youtube": {"player_client": ["android", "ios", "tv", "web"]},
        },
    }
    if _ffmpeg:
        base_opts["ffmpeg_location"] = _ffmpeg
    # YouTube often blocks downloads with "Sign in to confirm you're not a bot"
    # → needs login cookies. We try, in order:
    #   1. data/youtube_cookies.txt — user-exported Netscape cookies (reliable)
    #   2. no cookies (public videos still work)
    # We deliberately DON'T read cookies straight from Chrome: yt-dlp can't copy
    # Chrome's cookie DB while Chrome is running (yt-dlp #7271), and Chrome must
    # stay open for the Flow bridge — so cookies.txt is the route for gated videos.
    cookies_txt = DATA_DIR / "youtube_cookies.txt"

    # Auto-harvest fresh YouTube cookies from the user's Chrome via the
    # extension (chrome.cookies API → already decrypted, no DB-copy issue).
    # Best-effort: needs the extension connected with a labs.google tab.
    auto_cookies = tmp / "auto_cookies.txt"
    have_auto = False
    try:
        from ..services.browser_bridge import bridge as _bridge
        res = await _bridge.get_cookies([".youtube.com", ".google.com"])
        cks = (res or {}).get("cookies") or []
        if cks:
            _write_netscape_cookies(auto_cookies, cks)
            have_auto = True
            log.info(f"yt-dlp: harvested {len(cks)} Chrome cookies via extension")
        else:
            # No cookies → usually: extension chưa reload lên bản có task
            # get_cookies, hoặc Chrome chưa đăng nhập YouTube. Log res để biết.
            log.warning(
                "yt-dlp: cookie harvest trả về 0 cookie — kiểm tra: extension đã "
                "Reload lên 1.2.2 chưa (task get_cookies) + đã đăng nhập YouTube "
                f"trong Chrome chưa? (res={str(res)[:200]})"
            )
    except Exception as e:
        log.warning(f"yt-dlp: extension cookie harvest lỗi: {str(e)[:160]}")

    def _download(mode: str):
        opts = dict(base_opts)
        if mode == "auto":
            opts["cookiefile"] = str(auto_cookies)
        elif mode == "file":
            opts["cookiefile"] = str(cookies_txt)
        with yt_dlp.YoutubeDL(opts) as ydl:
            return ydl.extract_info(body.url, download=True)

    modes = []
    if have_auto:
        modes.append("auto")
    if cookies_txt.exists():
        modes.append("file")
    modes.append("none")
    title = None
    duration = None
    info = None
    last_err = None
    for mode in modes:
        try:
            info = await asyncio.to_thread(_download, mode)
            break
        except Exception as e:
            last_err = e
            log.warning(f"yt-dlp youtube download (cookies={mode}) failed: {str(e)[:140]}")
            continue
    try:
        if info is None:
            raise last_err or RuntimeError("Download failed")
        title = info.get("title")
        duration = info.get("duration")
        downloaded = next(tmp.glob("video.*"), None)
        if not downloaded:
            raise RuntimeError("Download produced no file")
    except Exception as e:
        shutil.rmtree(tmp, ignore_errors=True)
        low = str(e).lower()
        if "sign in to confirm" in low or "not a bot" in low or "cookie" in low:
            raise HTTPException(500,
                "YouTube chặn tải video (yêu cầu đăng nhập). Cách 1: ĐĂNG NHẬP YouTube trong "
                "Chrome (cùng profile có extension RedOne, KHÔNG ẩn danh) — tool sẽ tự lấy cookie — "
                f"rồi thử lại. Cách 2 (dự phòng): export cookies.txt rồi lưu vào: {cookies_txt}"
            )
        raise HTTPException(500, f"Download failed: {e}")

    aliases = body.character_aliases or {}
    alias_lines = "\n".join(f"  {k}: {v}" for k, v in aliases.items()) or "  (none)"
    style = body.style_preset or "Cinematic"
    instruction = f"""Analyze this video and break it into scenes for Veo 3 video generation.

PLATFORM: {platform}
TITLE: {title}
DURATION: {duration}s

CHARACTERS:
{alias_lines}

STYLE: {style}
{('STYLE LOCK: ' + body.style_lock) if body.style_lock else ''}
{('GLOBAL CONTEXT: ' + body.global_context) if body.global_context else ''}
VOICE GENDER: {body.voice_gender}

Output a JSON array, max {body.max_scenes} scenes. For each: scene, shot, camera, characters, narration, prompt.
{'QUICK MODE: Brief narration only.' if body.quick_mode else 'Detailed narration with quotes if heard.'}
Shot types: Extreme Wide, Wide, Medium, Medium Close-Up, Close-Up, Extreme Close-Up, OTS, POV.
Camera moves: Static, Pan Left/Right, Tilt Up/Down, Zoom In/Out, Push In, Pull Out, Dolly, Tracking, Aerial.

Output ONLY the JSON array."""

    try:
        result = await generate_text(
            instruction,
            images=[downloaded],
            response_mime_type="application/json",
        )
        text = re.sub(r"^```(?:json)?\s*|\s*```$", "", result["text"].strip())
        scenes = json.loads(text)
        return {
            "platform": platform,
            "title": title,
            "duration": duration,
            "scenes": scenes,
            "model_used": result["model_used"],
            "fallback_log": result["fallback_log"],
        }
    except Exception as e:
        raise HTTPException(500, f"AI analysis failed: {e}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


@router.post("/youtube-upload")
async def analyze_uploaded_video(
    file: UploadFile = File(...),
    style_preset: str = Form("Cinematic"),
    max_scenes: int = Form(12),
):
    """Analyze a user-uploaded video file."""
    tmp = Path(tempfile.mkdtemp(prefix="navtools_upload_"))
    ext = Path(file.filename or "video.mp4").suffix
    out = tmp / f"video{ext}"
    with out.open("wb") as f:
        shutil.copyfileobj(file.file, f)
    try:
        instruction = f"""Analyze this uploaded video and break it into scenes for Veo 3 video generation.
STYLE: {style_preset}
Output a JSON array, max {max_scenes} scenes. For each: scene, shot, camera, characters, narration, prompt.
Output ONLY the JSON array."""
        result = await generate_text(
            instruction,
            images=[out],
            response_mime_type="application/json",
        )
        text = re.sub(r"^```(?:json)?\s*|\s*```$", "", result["text"].strip())
        scenes = json.loads(text)
        return {"scenes": scenes, "model_used": result["model_used"]}
    except Exception as e:
        raise HTTPException(500, f"Failed: {e}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# ---------------- Image-to-Prompt ----------------

@router.post("/image-to-prompt")
async def image_to_prompt(
    file: UploadFile = File(...),
    instruction: str = Form(""),
):
    tmp = Path(tempfile.mkdtemp(prefix="navtools_img_"))
    out = tmp / (file.filename or "image.png")
    with out.open("wb") as f:
        shutil.copyfileobj(file.file, f)
    try:
        text = await describe_image(out, instruction.strip() or None)
        return {"prompt": text}
    except Exception as e:
        raise HTTPException(500, f"Failed: {e}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
