WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:confluence-macro-api-v5', location = 'v5/js/confluence/utils.js' */
define("ac/confluence/utils",["document"],(function(t){"use strict";return{isFabricEditor:function(){return t.querySelectorAll("[data-fabric-mode]").length>0},getContentType:function(t,n,e){var o=JSON.stringify({contentIds:[n]});t.ajax({url:AJS.contextPath()+"/api/v2/content/convert-ids-to-types",method:"POST",contentType:"application/json",data:o}).done((function(t){t.results&&t.results[n]?e(t.results[n]):AJS.error("Content type not found for content ID: "+n)})).fail((function(){AJS.error("Failed to get content type for content ID: "+n)}))},isCustomContent:function(t){return/^(ac:|forge:)/.test(t)}}}));
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:confluence-macro-api-v5', location = 'v5/js/confluence/macro/macro.js' */
define("ac/confluence/macro",["confluence/root","ajs","ac/confluence/utils"],(function(o,e,r){const a=e.$;var t=void 0,n={};function c(){var o=require("confluence-macro-browser/macro-browser");void 0===o&&(o={getMacroName:function(o){},getMacroParams:function(o){},getMacroBody:function(){throw new Error("confluence-macro-browser/macro-browser is unavailable")}});return o}function i(o){const e=o.indexOf("=");if(e>0){return{key:o.slice(0,e),value:o.slice(e+1)}}return{}}function s(o){return o.split("|").reduce((function(o,e){const r=i(e);r.key&&(o[r.key]=r.value);return o}),{})}return{convertRawParamToObject:i,convertRawParamSeriesToObject:s,getMacroBody:function(o){var r=o._context.extension.options.productContext["macro.id"],t=a('[data-macro-body][data-fabric-macro="'+r+'"]');if(t.length)o(t.attr("data-macro-body")||"");else if(!n||"string"!=typeof n.body&&!Array.isArray(n.body))try{var i=c().getMacroBody(),s=a(a.parseXML('<root xmlns:ac="guid">'+i+"</root>")).find("[ac\\:macro-id='"+r+"']");if(1==s.length){o(s.html().replace('xmlns:ac="guid"',""));return}o(i);return}catch(a){var u=o._context.extension.options.productContext;if("false"===u["macro.truncated"]){o(u["macro.body"]);return}var d=u["page.id"],m=u["page.version"];e.$.ajax({url:e.contextPath()+"/rest/api/content/"+d+"/history/"+m+"/macro/id/"+r,dataType:"json",success:function(e){o(e.body)}})}else o(n.body)},closeCurrentMacroPropertyPanel:function(){e.Confluence.PropertyPanel.destroy()},setLastSelectedConnectMacroNode:function(o){n.locationToInsert=void 0;n.params=void 0;n.body=void 0;n.name=void 0;var e=c().getMacroName(o);t=void 0!==e?o:void 0},setUnsavedMacroData:function(o,e,r,a){n.body=e;n.params=r;n.locationToInsert=a;n.name=o},clearMacroDataParams:function(){n.params=null},getMacroData:function(o){var e=o._context.extension.options.productContext["macro.id"],r=a('[data-fabric-macro="'+e+'"]');if(r.length)o(JSON.parse(r.attr("data-macro-parameters")||"{}"));else if(void 0===t&&n.params)o(n.params);else if(t)o(c().getMacroParams(t));else{o(s(o._context.extension.options.productContext[": = | RAW | = :"]||""))}},getCurrentMacroParameters:function(){return void 0===t?n.params:c().getMacroParams(t)},saveMacro:function(){return tinymce.confluence.MacroUtils.updateMacro.apply(this,arguments)},saveCurrentMacro:function(a,i){if(r.isFabricEditor()){return require("confluence-macro-browser/macro-browser-facade").insert({name:n.name,params:a,body:i})}if(void 0===t){n.params=a;n.body=i;var s={contentId:o.getContentId(),macro:{name:n.name,params:n.params,body:null===n.body?"":n.body}};e.Rte.getEditor().selection.moveToBookmark(n.locationToInsert);return tinymce.confluence.MacroUtils.insertMacro(s).done((function(o){t=o}))}var u=c().getMacroName(t);if(void 0!==u)return tinymce.confluence.MacroUtils.updateMacro(a,i,u,t).done((function(o){t=o}))}}}));
}catch(e){WRMCB(e)};